name: Build & SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: Build and Analyze (SonarQube)
    runs-on: ubuntu-latest   # Windows avoid pannrom (stable)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- .NET API ----------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore API
        run: dotnet restore API/TIMEAPI.sln

      - name: Build API
        run: dotnet build API/TIMEAPI.sln --configuration Release --no-restore

      # ---------- UI (Angular) ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install UI deps
        working-directory: UI
        run: npm install

      - name: Build UI
        working-directory: UI
        run: npm run build --if-present

      # ---------- SONARQUBE ----------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
